# CONFIGURATION PARAMETERS

# Test case generator
generator=FT

# Number of test cases to be generated per operation on each iteration
testsperoperation=10

# OAS specification
oas.path=./openapi.json

# Test configuration file
conf.path=./testConf.json

# Directory where the test cases will be generated
test.target.dir=./test_classes

# Package name
test.target.package=fuzzing

# Experiment name (for naming related folders and files)
experiment.name=fuzzing

# Name of the test class to be generated
testclass.name=fuzzing_Test

# Measure input coverage
coverage.input=false

# Measure output coverage
coverage.output=false

# Enable CSV statistics
stats.csv=false

# Maximum number of test cases to be generated
numtotaltestcases=-1

# Optional delay between each iteration (in seconds)
delay=-1

# Ratio of faulty test cases to be generated (negative testing)
faulty.ratio=0

# Logging enabled
logToFile=true
