# API name
api=<API_NAME>

# CONFIGURATION PARAMETERS

# Test case generator
generator=FT

# Number of test cases to be generated per operation on each iteration
testsperoperation=10

# OAS specification
oas.path=<PATH_TO_OAS>

# Test configuration file
conf.path=<PATH_TO_CONF_FILE>

# Directory where the test cases will be generated
test.target.dir=src/generation/java/<API_NAME>_FT

# Package name
test.target.package=<API_NAME>_ft

# Experiment name (for naming related folders and files)
experiment.name=<API_NAME>_ft

# Name of the test class to be generated
testclass.name=<API_NAME>_ft_Test

# Measure input coverage
coverage.input=false

# Measure output coverage
coverage.output=false

# Enable CSV statistics
stats.csv=false

# Maximum number of test cases to be generated
numtotaltestcases=-1

# Optional delay between each iteration (in seconds)
delay=-1

# Ratio of faulty test cases to be generated (negative testing)
faulty.ratio=0

# Logging enabled
logToFile=true
