llm:
  model_path: "model/Llama-3.2-3B-Instruct-Q4_K_M.gguf" # Path to the local LLM
  temperature: 0.3
  device: "cpu" # "cpu", "cuda", or "auto"
  max_tokens: 256
  n_ctx: 1024
  n_threads: 8
  n_batch: 256

generation:
  n_valid_values: 6
  n_invalid_values: 1
